path:
  to:
    attachments: attachments
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: workforge
            client-secret: Shtvg0EesyjFqjLXC9ARXPVIOogRC8dc
            scope: openid
            authorization-grant-type: password
        provider:
          keycloak:
            token-uri: http://localhost:8180/realms/auth-realm/protocol/openid-connect/token
  redis:
    host: localhost
    port: 6379
    password: ""
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
        max-wait: 10000ms
  datasource:
    url: jdbc:postgresql://localhost:32768/workforge
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.security: DEBUG
